#配置文件
#服务配置:设置GIN的运行模式，默认http监听端口，允许读取和写入的最大持续时间
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

#App配置:设置默认每页数量，允许最大每页数量，默认应用日志存储路径
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  #上传文件所需配置
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

#数据库配置：连接数据库的必须基础参数
Datebase:
  DBType: mysql
  Username: root
  Password: xxxxxxx
  Host: 10.0.100.71:3307
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

#写入JWT的配置项：
JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200

#Email配置项
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 28399@qq.com
  Password: txxj
  IsSSL: true
  From: 28399@qq.com
  To:
    - 28399@qq.com