#配置文件
#服务配置:设置GIN的运行模式，默认http监听端口，允许读取和写入的最大持续时间
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

#App配置:设置默认每页数量，允许最大每页数量，默认应用日志存储路径
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

#数据库配置：连接数据库的必须基础参数
Datebase:
  DBType: mysql
  Username: root
  Password: rootroot
  Host: 10.0.100.71:3307
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30