app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "119.3.103.66"
  port: 3306
  user: test
  password: "Ln889040ln"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idel_conns: 50

redis:
  host: "119.3.103.66"
  port: 6379
  db: 0
  password: "CWwOAKbfNhq6d6Cc"
  pool_size: 100